[package]
name = "cpstt"
version = "0.1.0"
authors = ["xryuseix <ryusei143.shootingstar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
